#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

usage() {
  cat <<'EOF'
Usage: scripts/deploy/rollback.sh --role <app|python|sso> [--config <path>]

Rollback/cleanup helper for partially applied deployments.
It removes services/config generated by setup scripts so you can restart cleanly.
EOF
}

ROLE=""
CONFIG_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role)
      ROLE="${2:-}"
      shift 2
      ;;
    --config)
      CONFIG_PATH="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      err "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${ROLE}" ]]; then
  err "--role is required"
  usage
  exit 1
fi

if [[ -n "${CONFIG_PATH}" ]]; then
  if [[ ! -f "${CONFIG_PATH}" ]]; then
    err "Config file not found: ${CONFIG_PATH}"
    exit 1
  fi
  # shellcheck source=/dev/null
  set -a
  source "${CONFIG_PATH}"
  set +a
fi

require_root

case "${ROLE}" in
  app)
    print_header "Rollback - App server"
    systemctl stop apache2 2>/dev/null || true
    a2dissite mxa-transcription.conf 2>/dev/null || true
    rm -f /etc/apache2/sites-available/mxa-transcription.conf
    systemctl reload apache2 2>/dev/null || true

    # keep PostgreSQL package installed; just remove app DB/user if present
    DB_NAME="${DB_NAME:-transcription_db}"
    DB_USER="${DB_USER:-transcription_user}"
    sudo -u postgres psql -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${DB_NAME}' AND pid<>pg_backend_pid();" 2>/dev/null || true
    sudo -u postgres psql -c "DROP DATABASE IF EXISTS ${DB_NAME};" 2>/dev/null || true
    sudo -u postgres psql -c "DROP ROLE IF EXISTS ${DB_USER};" 2>/dev/null || true

    APP_DIR="${APP_DIR:-/opt/mxa-transcription}"
    rm -rf "${APP_DIR}/php-app" "${APP_DIR}/database"
    info "App rollback complete."
    ;;

  python)
    print_header "Rollback - Python server"
    systemctl stop transcription-api transcription-worker redis-server 2>/dev/null || true
    systemctl disable transcription-api transcription-worker 2>/dev/null || true
    rm -f /etc/systemd/system/transcription-api.service /etc/systemd/system/transcription-worker.service
    systemctl daemon-reload

    PY_DIR="${PY_DIR:-/opt/mxa-transcription/python-backend}"
    rm -rf "${PY_DIR}/.venv"
    rm -f "${PY_DIR}/.env"
    info "Python rollback complete."
    ;;

  sso)
    print_header "Rollback - SSO server"
    systemctl stop keycloak 2>/dev/null || true
    systemctl disable keycloak 2>/dev/null || true
    rm -f /etc/systemd/system/keycloak.service
    systemctl daemon-reload

    KC_DB_NAME="${KC_DB_NAME:-keycloak_db}"
    KC_DB_USER="${KC_DB_USER:-keycloak_user}"
    sudo -u postgres psql -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='${KC_DB_NAME}' AND pid<>pg_backend_pid();" 2>/dev/null || true
    sudo -u postgres psql -c "DROP DATABASE IF EXISTS ${KC_DB_NAME};" 2>/dev/null || true
    sudo -u postgres psql -c "DROP ROLE IF EXISTS ${KC_DB_USER};" 2>/dev/null || true

    rm -rf /opt/keycloak
    info "SSO rollback complete."
    ;;

  *)
    err "Unknown role: ${ROLE}"
    usage
    exit 1
    ;;
esac

